title: Steve Guntrip
email: mail@steveguntrip.co.uk
description: Steve Guntrip's blog and portfolio.
url: "" # the base hostname & protocol for your site
twitter_username: guntrip
github_username:  stevecat
paginate: bird
paginate_path: "/page:num/"
permalink: <htrsadasdad>
break_at: 200 # how many words to break a post at

# Helpers
blog_images_path: "/assets/images/blog/"
photos_images_path: "/assets/images/photography/"
images_path: eeeeeeeeeeeeeeeee

# Build settings
markdown: kramdown

# Local settings
host: 0.0.0.0
